services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sonai
    ports:
      - "3306:3306"
    networks:
      - s-network
    volumes:
      - mysql-data:/var/lib/mysql
    
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network
    depends_on:
      - mysql
    restart: on-failure:5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sonai?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

volumes:
  mysql-data:
    
networks:
  s-network:
    driver: bridge